### ISSUE TITLE
Further development?

### ISSUE THREAD

**Issue by SinaMirrazavi** [CarletonABL/QuIK#1]
Hi All, 

I attended the talk in ICRA 2023 and it is indeed a great toolbox. I was wondering if there will be a further development on this package including two points:

1- Having a pybind interface?
2- Having an interface to read the URDF file instead of setting the DH parameters? (Actually which convention of DH parameters do you use?)

Best
Sina

**Comment by steffanlloyd** [comment]
Hey Sina, I know this is long overdue, I completely missed this comment (must have the notifications set up wrong in Github).

I'll be publishing a larger update in the coming days, with improved usability, integration with ROS2 and CMake, and will work to add new features in the future. However, the DH table interface will stay: it's part of the reason why this algorithm is so fast, the forward kinematic processing is more efficient when using DH parameters. I may look in the future at providing a python script for automatic conversion from URDF to DH, but this is not an easy thing to do as there are many possible DH tables for a given URDF. Furthermore, it's not always possible to put the joints in the exact same alignment as how you had them set up in the URDF (even if the result is mathematically equivalent, only with a 90 degree rotation or inversion of the axes).

Hope this helps. Best.
